---
abstract: 'Perl extension for implement the apriori algorithm of data mining.'
author:
  - 'Alex Graciano <agraciano@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.3, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-Mining-Apriori
no_index:
  directory:
    - t
    - inc
requires:
  Algorithm::Combinatorics: '0.27'
resources:
  bugtracker: https://github.com/alexgracianoarj/data-mining-apriori/issues
  homepage: https://alexgracianoarj.github.io/data-mining-apriori
  repository: https://github.com/alexgracianoarj/data-mining-apriori
version: 0.17
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
